version: '3'
services:
  mongoDB:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: database
    networks:
      - express-backend
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./mongo-data:/data/db
  
  backend:
    build: .
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - MONGO_URL=mongodb://mongoDB:27017
    networks:
      - express-backend
    depends_on:
      - mongoDB

networks:
  express-backend:
    driver: bridge

volumes:
  mongo-data:
    driver: local